name: test pr

on:
  push:
  pull_request_target: 

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    steps:
      - uses: actions/checkout@v6

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git checkout -b foo
          touch bar
          git add bar
          git commit -am "test"
          git remote set-url origin https://x-access-token:${{ secrets. GITHUB_TOKEN}}@github.com/cjdcordeiro/ci-playground.git
          git push origin foo
