name: test pr

on:
  push:

jobs:
  hi:
    runs-on: ubuntu-latest
    name: hi job
    outputs:
      secret: ${{ steps.secrets.outputs.secret }}
    steps:
      - id: secrets
        run: |
          SECRET=$(($RANDOM))
          echo $SECRET
          SECRET_HANDLE=$(sha256sum <<< $SECRET | cut -d' ' -f1)
          echo $SECRET_HANDLE
          
          echo "::add-mask::$SECRET_HANDLE"
          echo "secret=$SECRET_HANLE" >> $GITHUB_OUTPUT
  bye:
    runs-on: ubuntu-latest
    needs: [ hi ]
    steps:
      - run: echo ${{ needs.hi.outputs.secret }}
